# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c85904c334499515355131da98daf0688920a67df11b1f524b2570f59cf788abafb366ef6598a680ca56c1a81f866ad27b3af46ded0856ad9493040c90d4b1f

test:
  secret_key_base: f086958c966abdfc63d5095cbf0fb1011179c1e9cfc0caa2b4dd942a0b1711dd8b648d235958195097c69040353aab2cddd3ef1712f1c646b899d434348d3446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
